# RGB-D Salient Object Detection (RGB-D SOD)
# Run: python train.py --config configs/rgbd_sod.yaml

# --- task-specific ---
train_path: 'C:\Projects\datasets\RGBD_SOD\NJU2K_NLPR\NJU2K_NLPR_Train'
save_path: '.\checkpoints\RGBD_SOD\'
epoch: 5
lr: 1.0e-4

# --- shared ---
hiera_path: '.\sam2\sam2.1_hiera_large.pt'
checkpoint: ''        # optional path to resume / fine-tune from
size: 352             # 352, 512, 1024
batch_size: 24
weight_decay: 5.0e-4
num_workers: 4
